### ISSUE TITLE
tst/200_LoadPackage.tst

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CategoryConstructor#25]
Where does the file `tst/200_LoadPackage.tst` come from? If it's created manually, you should use the capabilities of `PackageJanitor` to load the packages in `100_LoadPackage.tst`.

**Comment by mohamed-barakat** [comment]
I already added `Locales` and `SubcategoriesForCAP` to `ci_additional_repositories`. Where shall I add them in order to be automatically added to `100_LoadPackage.tst`?

**Comment by zickgraf** [comment]
`tests_additional_packages_to_load`, e.g. https://github.com/homalg-project/PackageJanitor/blob/c2df2349a201a195b7e81c74ce41588484347a0e/site.yml#L213

**Comment by mohamed-barakat** [comment]
Thanks 👍🏽
